
name: iOS Test Build

on:
  push:
    branches:
      - main

env:
  SCHEME: "Firebase_Demo"  # Replace with your Xcode scheme
  DESTINATION: "platform=iOS Simulator,name=Any iOS Device,OS=latest"

jobs:
  build:

    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
	  
    - name: Set up Xcode
      uses: nightstory/setup-xcodegen@v1
      with:
          enable-cache: true
          version: latest

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        bundle exec pod install

    - name: Build and test
      run: |
        xcodebuild clean build -workspace Firebase_Demo.xcworkspace -scheme $SCHEME -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
